#!/bin/bash

PUBLIC_AVAIL=$(expr `df -h | grep data | awk '{ a = $2 } END {print a }'`)
PUBLIC_USED=$(expr `df -h | grep data | awk '{ a = $3 } END {print a }'`)
PUBLIC_FREE=$(expr `df -h | grep data | awk '{ a = $4 } END {print a }'`)
PUBLIC_PCT=$(expr `df -h | grep data | awk '{ a = $5 } END {print a }'`)
DOCKER_CONTAINERS=$(</etc/update-motd.d/docker-stats.txt)

echo "

"

cat /etc/update-motd.d/banner.txt | toilet -f term --gay

        # Show Swap Values
        #Swap: `free -m | tail -n 1 | awk {'print $4'}`M | `free -m | tail -n 1 | awk {'print $2'}`M
cat << EOF

	Uptime: `uptime -p | sed 's/up //'`
	Memory: `free -h | awk '/^Mem:/ {printf "Total: %s | Used: %s | Available: %s", $2, $3, $7}'`
	CPU: `uptime | awk -F'average: ' '{ split($2, loads, ", "); printf "1 min: %s | 5 min: %s | 15 min: %s", loads[1], loads[2], loads[3] }'`
        Public: $PUBLIC_USED used | $PUBLIC_AVAIL avail. | $PUBLIC_FREE free | $PUBLIC_PCT 
$DOCKER_CONTAINERS

EOF
