#!/bin/bash

UPTIME_DAYS=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 / 86400)
UPTIME_HOURS=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 % 86400 / 3600)
UPTIME_MINS=$(expr `cat /proc/uptime | cut -d '.' -f1` % 31556926 % 86400 % 3600 / 60)
PUBLIC_AVAIL=$(expr `df -h | grep sda1 | awk '{ a = $2 } END {print a }'`)
PUBLIC_USED=$(expr `df -h | grep sda1 | awk '{ a = $3 } END {print a }'`)
PUBLIC_FREE=$(expr `df -h | grep sda1 | awk '{ a = $4 } END {print a }'`)
PUBLIC_PCT=$(expr `df -h | grep sda1 | awk '{ a = $5 } END {print a }'`)
DOCKER_CONTAINERS=$(</etc/update-motd.d/docker-stats.txt)

echo "

"

cat /etc/update-motd.d/banner.txt | toilet -f term --gay

        # Show Swap Values
        #Swap: `free -m | tail -n 1 | awk {'print $4'}`M | `free -m | tail -n 1 | awk {'print $2'}`M
cat << EOF

        Uptime: $UPTIME_DAYS days, $UPTIME_HOURS hours, $UPTIME_MINS minutes
        Memory: `free -m | head -n 2 | tail -n 1 | awk {'print $4'}`M | `free -m | head -n 2 | tail -n 1 | awk {'print $2'}`
        CPU: `cat /proc/loadavg | awk '{print $1 ", " $2 ", " $3 " (1, 5, 15 min)"}'`
        Public: $PUBLIC_USED used | $PUBLIC_AVAIL avail. | $PUBLIC_FREE free | $PUBLIC_PCT 
$DOCKER_CONTAINERS

EOF
